### ISSUE TITLE
createAssetFromFiles upload bug

### ISSUE THREAD

**Issue by NoahHahm** [contentful/contentful-management.js#165] opened 2018-04-23 12:34 UTC
const fs = require('fs');    
    const spaceEnvironment = await space.getEnvironment('master');
    spaceEnvironment.createAssetFromFiles({
        fields: {
          title: {
            'en': 'Asset title'
          },
          description: {
            'en': 'Asset description'
          },
          file: {
            'en': {
              contentType: 'application/octet-stream',
              fileName: 'sample',
              file: fs.createReadStream("/Users/user/Documents/sample")
            }
          }
        }
      })
      .catch(console.error);

-------------------
result

null: TypeError: Converting circular structure to JSON
message: "Converting circular structure to JSON"
stack: "TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at errorHandler (/Users/user/Documents/GitHub/zepeto-service-api/node_modules/contentful-management/dist/contentful-management.node.js:12376:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)"
__proto__: Error {constructor: , name: "TypeError", message: "", …}
constructor: function TypeError() { … }
message: ""
name: "TypeError"
toString: function toString() { … }
__proto__: Object {constructor: , name: "Error", message: "", …}

**Comment by alampros** [comment] 2018-04-25 18:32
This seems to be due to a `404` returned from the environment endpoint.

According [the `environments` docs](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/environments):
> This feature is only available with subscriptions created since 16th April 2018.

Does this mean that you will have to have a paid subscription in order to programmatically upload assets when v6 is released?

**Comment by axe312ger** [comment] 2018-04-26 08:15
No worries. If you can't use environments yet, you should be able to switch your old free subscription to the new free subscription to enable environments. Just go to `Organization Settings` in our web app. There you find your subscription models.

**Comment by axe312ger** [comment] 2018-04-26 08:30
I tried it out and can confirm the bug. We will investigate.

**Comment by jugglingthebits** [comment] 2018-05-04 16:11
I can confirm that this is due to a 404. `JSON.stringify(errorData, null, '  ')` in `errorHandler.js` is called with `errorData` containing a request object that appearantly has circular references.

**Comment by Khaledgarbaya** [comment] 2018-05-16 11:36
This is now fixed

**Closed by Khaledgarbaya** 2018-05-16 11:36 UTC
Labels: bug

**Comment by jugglingthebits** [comment] 2018-05-17 08:43
I can confirm that this works. I can now use `.getEnvironment('master')` even though I don't use the new pricing model yet. 👍
