### ISSUE TITLE
.getSpace() and .getSpaces() return a 500 error from the server

### ISSUE THREAD

**Issue by erinkav** [contentful/contentful-management.js#99] opened 2017-04-11 23:13 UTC
We're upgrading our version from 1.3.4 to v3.1.1 to use the upload API and are running into a 500 error  when we call the .getSpaces() and .getSpace() functions. 

Initially we received a vague error when sending the request. 

Console error: 
```
Server error occured. Waiting for 53824 ms before retrying....
```

We've logged out the functions and request is erroring out to a 500 status code on line 8065 in the contentful-management.node.js file. 

Versions:
    "contentful": "^3.5.0",
    "contentful-management": "^v3.1.1",

Code:
```
var cm = require('contentful-management')

let accessToken = '<accessToken>';

let options = {
  accessToken: accessToken
};


let client = cm.createClient(options);
client.getSpaces().then(spaces => {
  let spaceId = '<spaceId>';

  client.getSpace(this.spaceId)
  .then((space) => {
    let requests = [];
    this.space = space;
    console.log('space')
  });
});



```

**Comment by Khaledgarbaya** [comment] 2017-04-12 08:23
Hi @erinkav,
Most likely you have the wrong token. Can you try to click logout and then login when you are getting the management token from this link https://www.contentful.com/developers/docs/references/authentication/#the-management-api

Best,
Khaled

**Comment by alexxisroxxanne** [comment] 2017-04-13 18:35
Hi Khaled,

I'm having the same issue, but the problem isn't with the auth token. I ended up pulling down this repo to try to look into the issue further, and I decided to try running your tests.

The tests are broken, due to the import statement on line 11 in test/integration/integration-tests.js

I fixed the broken import by finding the correct module, and editing line 11 to the following:

```
import { createClient } from '../../lib/contentful-management'
```

When I tried to run the tests again, I got an error at line 38 in lib/contentful-management.js because the access token was undefined.
 
To address that, I manually set the access token in the params object on line 14 of the integration test file to both a real access token and a fake access token (literally 'access token') and I got the same result with both, which is the same error as above

```
Server error occured. Waiting for 3364 ms before retrying....
Server error occured. Waiting for 3222 ms before retrying....
Server error occured. Waiting for 3304 ms before retrying....
Server error occured. Waiting for 3214 ms before retrying....
```

**Comment by Khaledgarbaya** [comment] 2017-04-13 21:14
Hi @alexxisroxxanne and @erinkav ,

the accessToken is undefined because it is expected to be defined in a command line var which we do in the CI.
I agree that the SDK should not retry when there is an invalid accessToken which is fixed already [here](https://github.com/contentful/contentful-sdk-core/releases/tag/v3.8.2).
I am pretty much sure that there is a typo in the accessToken or in the space id you are providing.
We have an example app for direct file upload [here](https://github.com/contentful-labs/file-upload-example) which you can test live [here](https://contentful-labs.github.io/file-upload-example/)

**Comment by Khaledgarbaya** [comment] 2017-04-20 12:07
This is now fixed, the SDK will no retry when the wrong token is passed

**Closed by Khaledgarbaya** 2017-04-20 12:07 UTC
Labels: bug
