### ISSUE TITLE
VersionMismatch on .createAssetWithId

### ISSUE THREAD

**Issue by bencmbrook** [contentful/contentful-management.js#422] opened 2020-08-10 21:14 UTC
I believe this SDK is [meant to automatically include](https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/updating-and-version-locking) `X-Contentful-Version` when making create/update requests.

> Entries returned from `createEntryWithId` are wrapped using the `wrapEntry` function in `entities/Entry.js`, which does wrap each entry with `createEntryAPI`. The version is being sent in updates. 
> 
> Please open another issue if you continue to have problems with the version number being sent.

_Originally posted by @phoebeschmidt in https://github.com/contentful/contentful-management.js/issues/213#issuecomment-607733317_

I see that `environment.createAssetWithId` also is wrapped using the (similar) `wrapAsset` [function](https://github.com/contentful/contentful-management.js/blob/8d0662e529dbff41a15b77f42a6d82d7d137f4ed/lib/create-environment-api.ts#L584), however, I'm getting the `409 VersionMismatch` error when there is an existing asset. The stack trace also indicates that this header is missing altogether on my requests.

<img width="685" alt="Screen Shot 2020-08-10 at 5 18 06 PM" src="https://user-images.githubusercontent.com/7354176/89833182-a1567d80-db2e-11ea-8513-49d3c2aa326d.png">

**Comment by TimBeyer** [comment] 2020-11-11 11:28
If I understood you correctly, you experience this error when attempting to create an asset that already exists.  
In that case the error would be kind of expected, albeit misleading given the intent of creation.

The problem there would be that the API uses a `PUT /assets/:id` both for creation with a given ID and for updates of an entity with a given ID. When an entity is created, it of course also needs no `version` property since it's supposed to be new. 
However, if the entity already exists, then the API will assume that an update was intended and require the correct version.  

The only thing the SDK could do here in that case would be to see your intent to create the entity, catch the API error, and return a new 'Cannot create existing asset' error. The tricky thing about that is that the SDK currently is a rather thin wrapper around the API and generally just forwards API errors. So then this one error case would be behaving differently than all the other error cases, which would hurt consistency.

For now that's not something we would do for the single case of entity creations hitting existing entities, however it's a good thing to keep in mind for the future evolution of the SDKs.

**Comment by bencmbrook** [comment] 2020-11-11 19:23
Thanks for the response @TimBeyer — am I correct that `createEntryWithId` actually does pass `version` when an Entry already exists? I believe it was this inconsistency, where `createEntryWithId` upserts but `createAssetWithId` does not, that threw me off and prompted me to file this issue.

By the way, the quote in the original issue should have linked to this issue: https://github.com/contentful/contentful-management.js/issues/213#issuecomment-607733317

**Comment by TimBeyer** [comment] 2020-11-16 16:43
No,`createEntryWithId` does not pass the version.
See https://github.com/contentful/contentful-management.js/blob/master/lib/create-environment-api.ts#L458-L460

So I think it should return the same error.

**Comment by marcolink** [comment] 2021-11-15 10:57
Closing for now.

**Closed by marcolink** 2021-11-15 10:57 UTC
Labels: waiting for response
